### ISSUE TITLE
hg38.fa.genome

### ISSUE THREAD

**Issue by singha30** [hbctraining/variant_analysis#7]
please let me know how to get this file.   for calling the following command 
java -jar -Xmx4g $SNPEFF/snpEff.jar  eff \
-dataDir $DATADIR \
-cancer \
-noLog \
-csvStats $CSV_STATS \
-s $HTML_REPORT \
$REFERENCE_DATABASE \
$FILTERED_VCF_FILE_WITH_PEDIGREE_HEADER \
> $SNPEFF_ANNOTATED_VCF_FILE

**Comment by Gammerdinger** [comment]
Hi singha30,

These course materials are still under active development, we are hoping to have them completed by early Summer 2024. The short answer is that the $SNPEFF_ANNOTATED_VCF_FILE is the output from MuTect2 after filtering and also after annotation from SNPeff. We hope this helps!

Best,
Will Gammerdinger

**Comment by singha30** [comment]
Command executed:

bcftools annotate --header-lines /Data/data/raja/cfdna/nextflow1/bin/syn3_header.txt LCR_FILTERED > FILTERED_hd.vcf
**java -jar -Xmx4g /Data/data/raja/cfdna/nextflow1/bin/snpEff/snpEff.jar eff -dataDir /Data/data/raja/cfdna/nextflow1/bin
/snpEff/data -cancer -noLog -csvStats CSV_STATS -s HTML_REPORT /Data/data/raja/cfdna/nextflow1/bin/snpEff/Data/data/GRCh38.p14 FILTERED_hd.vcf > SNPEFF_ANNOTATED.vcf**
java -jar /Data/data/raja/cfdna/nextflow1/bin/SNPEFF/SnpSift.jar annotate /Data/data/raja/cfdna/nextflow1/bin/snpEff/DBS
NP_DATABASE -tabix -noLog SNPEFF_ANNOTATED.vcf > DBSNP_ANNOTATED.vcf

Command exit status:
255

Command output:
(empty)

### Command error:
**java.lang.RuntimeException: Property: '/Data/data/raja/cfdna/nextflow1/bin/snpEff/Data/data/GRCh38.p14.genome' not found**
at org.snpeff.interval.Genome.(Genome.java:103)
at org.snpeff.snpEffect.Config.readConfig(Config.java:757)
at org.snpeff.snpEffect.Config.init(Config.java:532)
at org.snpeff.snpEffect.Config.(Config.java:119)
at org.snpeff.SnpEff.loadConfig(SnpEff.java:449)
at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:883)
at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:869)
at org.snpeff.SnpEff.run(SnpEff.java:1173)
at org.snpeff.SnpEff.main(SnpEff.java:163)

1. error is show:-GRCh38.p14.genome' not found 
**can you please help how to generate this file  or fix the issue  **
